# Generated by Django 3.1.6 on 2021-10-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Menu',
        ),
    ]
